@echo off
echo 开始执行 Git 命令...
echo 检查 Git 状态...
git status
echo 添加所有修改的文件...
git add .
echo 提交修改...
git commit -m "fix: 修复资产系统类型不匹配并强制同步数据结构"
echo 推送到 GitHub...
git push origin main --force
echo 执行完成！
pause
